spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/video-service
  kafka:
    bootstrap-servers: broker:29092
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
