spring:
  application:
    name: video-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/video-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
