spring:
  application:
    name: video-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/video-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": event:com.zeljko.videoservice.event.VideoProgressMessage
        spring.json.trusted.packages: "*"
    template:
      default-topic: video-progress
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com:
      zeljko:
        videoservice:
          service:
            VideoService: DEBUG
