spring:
  application:
    name: video-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/video-service
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
