eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka


server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/user_security
    username: root
    password: zeljkoo123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
